### ISSUE TITLE
[FEATURE] Decode EVM Transaction Call Data for User Readability

### ISSUE THREAD

**Issue by lmcmz** [onflow/FRW-Extension#232]
#EPIC
https://github.com/Outblock/FRW/issues/84

## Description  
This feature will enable users to view a decoded, human-readable structure of the EVM transaction call data they are about to sign.  

Currently, there is no simulator or decoder for transactions, making it difficult for users to understand the operations involved.  
- **When ABI is available:** The backend provides fully decoded transaction metadata.  
- **When ABI is unavailable:** The backend returns basic metadata with limited details.  

The client needs to handle the response and present the decoded data in the appropriate UI states.

---

## Acceptance Criteria  
- [ ] Display the decoded transaction metadata when ABI is available.  
- [ ] Display fallback metadata when ABI is unavailable.  
- [ ] Handle three UI states as per the design:
  1. Initial state.  
  2. Loading state.  
  3. Decoded transaction (with ABI or fallback for non-ABI).  
- [ ] Ensure seamless integration with the existing transaction-signing flow.  

---

### Client-Side Responsibilities  
1. **Send Transaction Data to Backend:**  
   - Ensure the full transaction object (including `calldata` and `contractAddress`) is sent to the backend API.  

2. **Handle Backend Response:**  
   - Parse the response to identify whether the decoding was performed with or without ABI.  
   - Update the UI based on the response.  

3. **UI States (Refer to Figma for Designs):**  
   - **Initial State:** Default screen before transaction data is sent.  
   - **Loading State:** Shown while waiting for backend decoding.  
   - **Decoded Transaction Display:**  
     - **With ABI:** Show detailed metadata for the operation.  
     - **Without ABI:** Show fallback metadata (e.g., raw calldata or method ID).  

---

## Feature Flag  
- **Flag Name:** `evm-tx-decoding`  
- **Default State:** Off.  
- **Rollout Plan:** Gradual rollout to users after QA validation.

---

## Tasks  
- [ ] **API Integration:**  
  - Implement API call to send transaction data to the backend.  
  - Handle backend responses for ABI and non-ABI cases.  

- [ ] **UI Updates:**  
  - Implement the initial, loading, and decoded states per the design.  
  - Ensure the UI correctly renders detailed metadata or fallback information.  

- [ ] **Error Handling:**  
  - Display a user-friendly message if decoding fails.

**Comment by Peppermint1020** [comment]
We need handle over the transaction amount to human readable text.
<img width="401" alt="Image" src="https://github.com/user-attachments/assets/786f18a8-da9f-4fc9-b78a-96a4e8c079fa" />
Already passed other tests:
(1)Sign trx with abi
<img width="384" alt="Image" src="https://github.com/user-attachments/assets/824e0d5a-cf89-4e19-8056-18dce77e1288" />

(2) Sign trx without abi
<img width="385" alt="Image" src="https://github.com/user-attachments/assets/a154f0c5-f502-4061-8ac9-3b0fb3a4796c" />

**Comment by Peppermint1020** [comment]
The above issue already solved in extension Version 2.6.6
Staging Commit: 2b71c53c928b19e3aa64c7bed8452901d6f0dc1d

<img width="404" alt="Image" src="https://github.com/user-attachments/assets/63d2cf26-19e7-48d4-b3d2-3c0fd57bbf73" />
